0902 commit
jonghwan-code/codingtest_programmers pull request #1
Opened 2023-09-02 06:50 UTC by jonghwan-code

Programmers Coing Test Python

2023-09-02 06:51 UTC, jonghwan-code commented
@f-lab-jake

2023-09-04 06:50 UTC, f-lab-jake requested changes

2023-09-04 06:50 UTC, f-lab-jake commented on 프로그래머스/lv1/12916. 문자열 내 p와 y의 개수/문자열 내 p와 y의 개수.py
> +    if 'p' in s or 'y' in s:
요건 뺄수있습니다.

2023-09-04 06:50 UTC, f-lab-jake commented on 프로그래머스/lv1/12934. 정수 제곱근 판별/정수 제곱근 판별.py
> +    if int(math.sqrt(n)) == math.sqrt(n):
`.sqrt`에는 정확도에 한계가 있습니다. 어떤경우에 문제가 생길까요? 그걸 어떻게 해결할수있나요?

2023-09-04 06:50 UTC, f-lab-jake commented on 프로그래머스/lv1/12943. 콜라츠 추측/콜라츠 추측.py
> +        elif x == 1:
위의 분기에서 `return` 등의 탈출 구문이있다면 `elif` 대신에 그냥 `if`를 써보세요. 그 방법이 왜 나을까요?

2023-09-04 06:50 UTC, f-lab-jake commented on 프로그래머스/lv1/12943. 콜라츠 추측/콜라츠 추측.py
> +        else:
요것도 마찬가지 입니다.

2023-09-04 06:50 UTC, f-lab-jake commented on 프로그래머스/lv1/12947. 하샤드 수/하샤드 수.py
> +        return True
한줄로 줄여봅시다.

2023-09-04 06:50 UTC, f-lab-jake commented on 프로그래머스/lv1/12954. x만큼 간격이 있는 n개의 숫자/x만큼 간격이 있는 n개의 숫자.py
> +        answer.append(answer[-1] + x)
인덱스 참조를 하지 않는 코드로 바꿔보세요. 어떤 장점이 있나요?

2023-09-04 07:21 UTC, jonghwan-code commented on 프로그래머스/lv1/12916. 문자열 내 p와 y의 개수/문자열 내 p와 y의 개수.py
> +    if 'p' in s or 'y' in s:
```python
    s = s.lower()
    p, y = (0, 0)
    for x in s:
        if x == 'p':
            p += 1
        elif x == 'y':
            y += 1
    if p == y:
        return True
    else:
        return False
    return True 
```
이렇게 수정을 해보는 건 어떨까요?

2023-09-04 07:43 UTC, jonghwan-code commented on 프로그래머스/lv1/12943. 콜라츠 추측/콜라츠 추측.py
> +        elif x == 1:
elif는 위에서 설정한 if 조건이 **아니면서** elif 조건인 경우에 해당하는데, 
if 조건에서 탈출 설정을 해놓고 굳이 elif를 사용하지 않아도 될 것 같습니다.

2023-09-04 07:45 UTC, jonghwan-code commented on 프로그래머스/lv1/12947. 하샤드 수/하샤드 수.py
> +        return True
```python
return Flase if x % tmpSum else True
```

요렇게 줄여볼 수 있을 것 같습니다.

2023-09-04 07:49 UTC, jonghwan-code commented on 프로그래머스/lv1/12954. x만큼 간격이 있는 n개의 숫자/x만큼 간격이 있는 n개의 숫자.py
> +        answer.append(answer[-1] + x)
조회도 결국 O(1)이라는 시간복잡도를 가지는 알고리즘이라서 비효율적일까요...?
```python
    for i in range(1, n + 1):
        answer.append(x * i)
```
인덱스 참조를 하지 않는 코드로 수정해 보았습니다!!

2023-09-04 08:02 UTC, jonghwan-code commented on 프로그래머스/lv1/12934. 정수 제곱근 판별/정수 제곱근 판별.py
> +    if int(math.sqrt(n)) == math.sqrt(n):
음수의 경우 sqrt가 에러를 발생하는 것 같습니다.
`num ** 1/2`를 사용하여 제곱근을 구하는 방법은 어떤가요?

2023-09-06 05:15 UTC, f-lab-jake requested changes

2023-09-06 05:15 UTC, f-lab-jake commented on 프로그래머스/lv1/12916. 문자열 내 p와 y의 개수/문자열 내 p와 y의 개수.py
> +    return True
요것도 줄일수있습니다

2023-09-11 04:06 UTC, f-lab-jake requested changes

2023-09-11 04:06 UTC, f-lab-jake commented on 프로그래머스/lv1/12910. 나누어 떨어지는 숫자 배열/나누어 떨어지는 숫자 배열.py
> +    return [-1] if len(answer) == 0 else answer
파이썬에서 빈 배열은 falsy value입니다

2023-09-11 14:13 UTC, jonghwan-code commented on 프로그래머스/lv1/12910. 나누어 떨어지는 숫자 배열/나누어 떨어지는 숫자 배열.py
> +    return [-1] if len(answer) == 0 else answer
요렇게 바꾸면 어떨까 싶습니다.
```suggestion
    return answer if len(answer) else [-1] 
```

2023-09-12 07:38 UTC, merged

2023-09-12 15:06 UTC, f-lab-jake commented on 프로그래머스/lv1/76501. 음양 더하기/음양 더하기.py
> +        result.append(absolutes[n] * 1) if signs[n] else result.append(absolutes[n] * -1)
같은 의미의 코드가 중복되어 나타납니다

2023-09-14 03:53 UTC, jonghwan-code commented on 프로그래머스/lv1/76501. 음양 더하기/음양 더하기.py
> +        result.append(absolutes[n] * 1) if signs[n] else result.append(absolutes[n] * -1)
```suggestion
        result.append(absolutes[n]) if signs[n] else result.append(-absolutes[n])
```
*1 *-1 부분을 위처럼 수정하면 될까요..?

2023-09-14 06:39 UTC, f-lab-jake commented on 프로그래머스/lv1/76501. 음양 더하기/음양 더하기.py
> +        result.append(absolutes[n] * 1) if signs[n] else result.append(absolutes[n] * -1)
글자 그대로 중복되는 부분이 있습니다. 그리고 그게 의미상으로도 중복입니다.

2023-09-18 07:53 UTC, f-lab-jake commented on 프로그래머스/lv1/12947. 하샤드 수/하샤드 수.py
> +        return True
근본적으론 똑같은 코드입니다. 개선이라고 보기 힘듭니다. 줄수만 줄이는게 아니고 의미자체를 줄여야합니다.
 if문을 쓰지 말아보세요

2023-09-18 07:55 UTC, f-lab-jake commented on 프로그래머스/lv1/12910. 나누어 떨어지는 숫자 배열/나누어 떨어지는 숫자 배열.py
> +    return [-1] if len(answer) == 0 else answer
`return answer if answer else [-1] `
이렇게 또는
`return answer or [-1]`이 가능합니다

2023-09-18 07:57 UTC, f-lab-jake commented on 프로그래머스/lv1/12954. x만큼 간격이 있는 n개의 숫자/x만큼 간격이 있는 n개의 숫자.py
> +        answer.append(answer[-1] + x)
사실 곱하기가 더하기보다 느리기때문에 이게 더 느릴수도 있습니다 있습니다
핵심은 `answer[-1]`을 쓰지않는것입니다.
인덱스 참조를 하는 코드는 틀리기 쉽습니다. 원래코드가 잘돌아가는건 `answer`가 빈배열이 아니기때문인데요. `answer`가 빈 배열일 경우가 없다는걸 확인하려면 코드 전체를 봐야합니다. 일부만보고도 안심할수있는 코드를 짜야합니다.
곱하기를 쓰지않으면서 `answer[-1]`을 쓰지안흔 코드를 짜보세요.

2023-09-19 03:08 UTC, jonghwan-code commented on 프로그래머스/lv1/12954. x만큼 간격이 있는 n개의 숫자/x만큼 간격이 있는 n개의 숫자.py
> +        answer.append(answer[-1] + x)
완전히 인덱스 참조를 안했다고 할 수 없네요;;; 곱하기와 [-1] 조회를 하지 않은 아래 코드도 마찬가지라 할 수 있을까요..?
```js
def solution(x, n):
    result = [x]
    for i in range(1, n):
        result.append(result[i-1] + x)
    return result
```

2023-09-19 03:11 UTC, jonghwan-code commented on 프로그래머스/lv1/12916. 문자열 내 p와 y의 개수/문자열 내 p와 y의 개수.py
> +    return True
이렇게 줄여서 다시 제출했습니다!

```js
return p == y
```

2023-09-19 03:13 UTC, jonghwan-code commented on 프로그래머스/lv1/12910. 나누어 떨어지는 숫자 배열/나누어 떨어지는 숫자 배열.py
> +    return [-1] if len(answer) == 0 else answer
아...! 맞네요!! 수정하여 재제출했습니다!

2023-09-19 03:25 UTC, jonghwan-code commented on 프로그래머스/lv1/76501. 음양 더하기/음양 더하기.py
> +        result.append(absolutes[n] * 1) if signs[n] else result.append(absolutes[n] * -1)
혹시 이것도 의미상 중복이 된 코드가 있을까요?

```python
def solution(absolutes, signs):
    sum = 0
    for num, b in zip(absolutes, signs):
        if b:
            sum += num
        else:
            sum -= num
    return sum

```